### ISSUE TITLE
Colocar um comentário neste issue com o link de acesso à aplicação já implantada.

### ISSUE THREAD

**Issue by tmsasaki** [leofsl/ppads-projeto-05K#10]

**Comment by FGDOURADO** [comment]
Professor, boa noite.

**Link da aplicação na nuvem via Amazon:** http://munka.sa-east-1.elasticbeanstalk.com/

**ATENÇÃO**: Por regras de negócios da nossa aplicação, existe um campo no cadastro chamado: 
 '**Empresa Associada (COD IDENTIFICADOR - MATRICULA)**, favor colocar com o padrão abaixo:

**OBSERVAÇÃO**: O código **0001** representa o Mackenzie e o código **0002** representa a PUC - > 
 (Escolha uma das duas instituições). É **obrigatório** ter essa sequência de números antes.

Inserir antes no campo: **0001** ou **0002**, o resto é você quem define, pois é questão de nomenclatura. Adotamos o padrão de nomenclatura abaixo:

**EXEMPLO**: 0001-MACKENZIE-31548245 ou 0002-PUCCAMPINAS-31548245

Qualquer dúvida estou a disposição.
