### ISSUE TITLE
O caso de uso "Fazer upload de imagem" NÃO é uma extensão dos outros dois casos de uso indicados na figura.

### ISSUE THREAD

**Issue by tmsasaki** [leofsl/ppads-projeto-05K#5]

**Comment by leofsl** [comment]
O caso de uso já foi ajustado conforme alinhado com o Professor Thomaz.

**Comment by tmsasaki** [comment]
Sugiro considerar que no caso de uso "Fazer upload de imagem" o sistema sempre sugere ao usuário incluir uma imagem, sendo que o usuário pode explicitamente escolher a opção de não fazer o upload.
