### ISSUE TITLE
Na criação do usuário, não deveria haver uma forma de validação por e-mail? Talvez aceitar apenas e-mails no formato @mackenzie.br ou @mackenzista.com.br

### ISSUE THREAD

**Issue by tmsasaki** [leofsl/ppads-projeto-05K#6]

**Comment by leofsl** [comment]
Na criação do usuário será exibido uma mensagem informando que seu cadastro será validado pelo Administrador, podendo ser aceito ou recusado. O formato será validado de acordo com a empresa do usuário.
